version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: licita_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staging_db
    ports:
      - "5432:5432"
    networks:
      - licita-network
    volumes:
      - postgres_data:/var/lib/postgresql/data



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: licita_backend
    network_mode: "${BACKEND_NETWORK_MODE:-bridge}"
    ports:
      - "5001:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=staging_db
      
      # --- CONFIGURAÇÃO DO BANCO DE PRODUÇÃO (LEGADO) ---
      - LEGACY_DB_HOST=162.240.98.204
      - LEGACY_DB_PORT=3306
      - LEGACY_DB_USER=wwbraz_bruno
      - LEGACY_DB_PASSWORD=0PmW%%ViB$$@; # $ escaped as $$
      - LEGACY_DB_NAME=wwbraz_prefeitura
      - LEGACY_TABLE_NAME=licitacao
      - PORT=${BACKEND_PORT:-3000}
    depends_on:
      - postgres
    networks:
      - licita-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5001}
    container_name: licita_frontend
    ports:
      - "5002:3000"
    depends_on:
      - backend
    networks:
      - licita-network

networks:
  licita-network:
    driver: bridge

volumes:
  postgres_data:

